spring.profiles.active = dev

spring.application.name=Proyecto2-HF
server.servlet.context-path = /proyecto2-hf/api

spring.datasource.driver-class-name=org.postgresql.Driver

langchain4j.open-ai.chat-model.model-name=gpt-4o-mini